server:
  host: "0.0.0.0"
  port: 8500
  maxHeaderBytes: 1
  readTimeout: 30s
  writeTimeout: 30s

portal:
  url: "https://portal.students.it-college.ru"
  attendanceURL: ""

auth:
  serviceURL: ""
  timeout: 5s